FROM node:22.16.0-alpine3.22

# Set working directory
WORKDIR /app

# Install pnpm
RUN corepack enable

# Copy package files and install them
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy source files and build the app
COPY . .

CMD ["pnpm", "dev", "--host"]
